---
output: pdf_document
params:
  data: NA
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}

library(knitr)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)

library(xtable)
options(xtable.comment = FALSE)


dat <- pivot_longer(data = params[["data"]], cols = -Compound) %>% 
  mutate(group_label = substr(name, 0, 2))

group_label <- unique(dat[["group_label"]])

shp_pval <- lapply(unique(dat[["Compound"]]), function(ith_cmp) {
  lapply(group_label, function(ith_group) {
    filter(dat, Compound == ith_cmp, group_label == ith_group) %>% 
      pull(value) %>% 
      shapiro.test() %>% 
      getElement("p.value") %>% 
      data.frame(Compound = ith_cmp, group_label = ith_group, pval = .)
  }) %>% 
    bind_rows()
}) %>% 
  bind_rows() %>% 
  mutate(apval = p.adjust(pval, method = "BH"))

dist_plot <- lapply(unique(dat[["Compound"]]), function(ith_cmp) {
  part_dat <- filter(dat, Compound == ith_cmp)
  
  hist <- ggplot(part_dat, aes(x = value, fill = group_label)) + 
    geom_histogram() +
    xlab("") +
    ggtitle("Histogram")
  
  qqplot <- ggplot(part_dat, aes(sample = value, color = group_label)) + 
    stat_qq() + 
    stat_qq_line() +
    ggtitle("Quantile-quantile chart")
  
  boxplot <- ggplot(part_dat, aes(x="", y = value, fill = group_label)) +
    geom_boxplot() +
    ggtitle("Boxplot")
  
  (hist + boxplot + qqplot)* facet_wrap(~ group_label, ncol = 1)* theme(legend.position = "bottom") + plot_annotation(paste0("Compound ", ith_cmp))
})


diff_pval_t <- sapply(unique(dat[["Compound"]]), function(ith_cmp) {
  filter(dat, Compound == ith_cmp) %>% 
    t.test(value ~ group_label, data = .) %>% 
    getElement("p.value")
}, USE.NAMES = FALSE) %>% 
  data.frame(Compound = unique(dat[["Compound"]]), pval = .) %>% 
  mutate(apval = p.adjust(pval, method = "BH"))


diff_pval_wilcox <- sapply(unique(dat[["Compound"]]), function(ith_cmp) {
  filter(dat, Compound == ith_cmp) %>% 
    wilcox.test(value ~ group_label, data = .) %>% 
    getElement("p.value")
}, USE.NAMES = FALSE) %>% 
  data.frame(Compound = unique(dat[["Compound"]]), pval = .) %>% 
  mutate(apval = p.adjust(pval, method = "BH"))

```



```{r, results='asis', fig.align='center', fig.height=6, fig.width=10, warning=FALSE, message=FALSE, echo=FALSE}

headers <- unique(dat[["Compound"]])
for (i in 1:length(headers)){
  cat("# Compound", headers[[i]], "\n")
  
  cat("## Normality", "\n")
  
  print(dist_plot[[i]])
  
  cat("#### Shapiro-Wilk Normality Test \n")
  
  print(kable(filter(shp_pval, Compound == headers[[i]])))
  
  
  cat("## Between groups comparison \n")
  
  cat("#### T-test: \n ")
  
  print(kable(filter(diff_pval_t, Compound == headers[[i]])))
  
  cat("#### Wilcoxon signed-rank test:\n")
  
  print(kable(filter(diff_pval_wilcox, Compound == headers[[i]])))
  
  cat("\\newpage")
  
}
```




